apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drink-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - admekb.ru
    - www.admekb.ru
    secretName: app-tls
  rules:
  - host: admekb.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drink-service
            port:
              number: 5000
